AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create an ECR repository with KMS Encrypted'
Parameters:
  MyRepositoryName:
    Description: Enter Name for the ECR Repository
    Type: String  
  Environment:
    Description: Environment (dev, staging, prod)
    Type: String 
  KMSKeyId: 
    Description: Enter the KMS Key ID to encrypt ECR Repository
    Type: String 

Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref MyRepositoryName
      EncryptionConfiguration: 
        EncryptionType: KMS
        KmsKey: !Ref KMSKeyId
      Tags:
        - Key: Name
          Value: !Ref MyRepositoryName
        - Key: Env
          Value: !Ref Environment

Outputs:
  ECRRepositoryArn:
    Description: "ARN of the created ECR repository"
    Value: !Ref MyECRRepository
