AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create an ECR repository with KMS Encrypted, allowing Reclaimz Ops Account to push Images to this Repo'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Project Name and Environment'
        Parameters:
          - ProjectName
          - Environment
          - TenantType
      - Label:
          default: 'ECR Parameters'
        Parameters:
          - MyRepositoryName
          - KMSKeyId
          - OpsAccountID
Parameters:
  ProjectName:
    Description: Name of the Project (ex- rczf, rczh)
    Type: String  
  Environment:
    Description: Environment (ex- dev, staging, qa, prod)
    Type: String     
  TenantType:
    Description: Tenant Type of the project (ex- finance, health)
    Type: String 
  MyRepositoryName:
    Description: Enter Name for the ECR Repository
    Type: String  
  KMSKeyId: 
    Description: Enter the KMS Key ID to encrypt ECR Repository
    Type: String 
  OpsAccountID:
    Description: AWS Account ID for Ops
    Type: String
    Default: 767397957166  

Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref MyRepositoryName
      RepositoryPolicyText: 
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "AllowCrossAccountPush",
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::${OpsAccountID}:root"
                  },
                  "Action": [
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:CompleteLayerUpload",
                    "ecr:InitiateLayerUpload",
                    "ecr:PutImage",
                    "ecr:UploadLayerPart"
                  ]
              }
            ]
          }
      EncryptionConfiguration: 
        EncryptionType: KMS
        KmsKey: !Ref KMSKeyId
      Tags:
        - Key: Name
          Value: !Ref MyRepositoryName
        - Key: Environment
          Value: !Ref Environment
        - Key: TenantType  
          Value: !Ref TenantType
        - Key: Project
          Value: !Ref ProjectName           

Outputs:
  ECRRepositoryArn:
    Description: "ARN of the created ECR repository"
    Value: !GetAtt MyECRRepository.Arn
  ECRRepositoryUri:
    Description: "URI of the created ECR repository"
    Value: !GetAtt MyECRRepository.RepositoryUri