AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for Redis Cluster with KMS encryption'

Parameters:
  VpcId:
    Description: "The VPC ID for the Redis cluster"
    Type: String
  Subnet1Id:
    Description: "The first subnet ID for the Redis cluster"
    Type: String
  Subnet2Id:
    Description: "The second subnet ID for the Redis cluster"
    Type: String
  SecurityGroupId:
    Description: "The security group ID for the Redis cluster"
    Type: String
  RedisNodeType:
    Description: "The instance type for the Redis nodes"
    Type: String
    Default: "cache.t3.micro"
  RedisClusterName:
    Description: "The name of the Redis cluster"
    Type: String
    Default: "my-redis-cluster"
  RedisNumShards:
    Description: "The number of shards in the Redis cluster"
    Type: Number
    Default: 1
  RedisNumReplicas:
    Description: "The number of replicas per shard"
    Type: Number
    Default: 1
  KmsKeyId:
    Description: "The KMS key ID for encryption"
    Type: String

Resources:
  RedisSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties: 
      Description: "Subnet group for Redis cluster"
      SubnetIds: 
        - Ref: Subnet1Id
        - Ref: Subnet2Id
      CacheSubnetGroupName: 
        !Sub "${RedisClusterName}-subnet-group"

  RedisSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: "Security group for Redis cluster"
      VpcId: 
        Ref: VpcId
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0

  RedisReplicationGroup:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties: 
      ReplicationGroupId: 
        Ref: RedisClusterName
      ReplicationGroupDescription: "Redis replication group"
      CacheNodeType: 
        Ref: RedisNodeType
      Engine: "redis"
      NumNodeGroups: 
        Ref: RedisNumShards
      ReplicasPerNodeGroup: 
        Ref: RedisNumReplicas
      CacheSubnetGroupName: 
        Ref: RedisSubnetGroup
      SecurityGroupIds: 
        - Ref: SecurityGroupId
      AutomaticFailoverEnabled: true
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      KmsKeyId: 
        Ref: KmsKeyId

Outputs:
  RedisClusterPrimaryEndpoint:
    Description: "Primary endpoint address of the Redis cluster"
    Value: 
      !GetAtt 
        - RedisReplicationGroup
        - PrimaryEndPoint.Address

  RedisClusterReaderEndpoint:
    Description: "Reader endpoint address of the Redis cluster"
    Value: 
      !GetAtt 
        - RedisReplicationGroup
        - ReaderEndPoint.Address
