AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for Redis Cluster with KMS encryption'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Project Name and Environment'
        Parameters:
          - ProjectName
          - Environment
          - TenantType
      - Label:
          default: 'Redis Parameters'
        Parameters:
          - VPCId
          - Subnet1Id
          - Subnet2Id
        #  - SecurityGroupId
          - RedisNodeType
          - RedisClusterName
          - RedisNumShards
          - RedisNumReplicas
          - KmsKeyId
          - RedisUserGroupName
          - SourceCidr
Parameters:
  ProjectName:
    Description: Name of the Project (ex- rczf, rczh)
    Type: String  
  Environment:
    Description: Environment (dev, staging, qa, prod)
    Type: String
  TenantType:
    Description: Tenant Type of the project (ex- finance, health)
    Type: String
  VpcId:
    Description: "The VPC ID for the Redis cluster"
    Type: String
  Subnet1Id:
    Description: "The first subnet ID for the Redis cluster"
    Type: String
  Subnet2Id:
    Description: "The second subnet ID for the Redis cluster"
    Type: String
  # SecurityGroupId:
  #   Description: "The security group ID for the Redis cluster"
  #   Type: String
  RedisNodeType:
    Description: "The instance type for the Redis nodes"
    Type: String
    Default: "cache.t3.micro"
  RedisClusterName:
    Description: "The name of the Redis cluster"
    Type: String
    Default: "my-redis-cluster"
  RedisNumShards:
    Description: "The number of shards in the Redis cluster"
    Type: Number
    Default: 1
  RedisNumReplicas:
    Description: "The number of replicas per shard"
    Type: Number
    Default: 1
  KmsKeyId:
    Description: "The KMS key ID for encryption"
    Type: String
  RedisUserGroupName:
    Description: "Enter the Name/ID of Redis User Group which is already created"
    Type: String      
  SourceCidr:
    Description: "The Source CIDR block or IP address for Redis security group"
    Type: String    

Resources:
  RedisSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties: 
      Description: "Subnet group for Redis cluster"
      SubnetIds: 
        - Ref: Subnet1Id
        - Ref: Subnet2Id
      CacheSubnetGroupName: 
        !Sub "${RedisClusterName}-subnet-group"
      Tags: 
        - Key: Environment
          Value: !Ref Environment
        - Key: TenantType  
          Value: !Ref TenantType
        - Key: Project
          Value: !Ref ProjectName        

  RedisSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupName: !Sub "${RedisClusterName}-sg"   
      GroupDescription: "Security group for Redis cluster"
      VpcId: 
        Ref: VpcId
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: !Ref SourceCidr
      Tags:
        - Key: Name
          Value: !Sub "${RedisClusterName}-sg" 
        - Key: Environment
          Value: !Ref Environment
        - Key: TenantType  
          Value: !Ref TenantType
        - Key: Project
          Value: !Ref ProjectName          

  RedisReplicationGroup:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties: 
      ReplicationGroupId: 
        Ref: RedisClusterName
      ReplicationGroupDescription: "Redis replication group"
      CacheNodeType: 
        Ref: RedisNodeType
      Engine: "redis"
      NumNodeGroups: 
        Ref: RedisNumShards
      ReplicasPerNodeGroup: 
        Ref: RedisNumReplicas
      CacheSubnetGroupName: 
        Ref: RedisSubnetGroup
      SecurityGroupIds: 
        - Ref: RedisSecurityGroup
      AutomaticFailoverEnabled: true
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      KmsKeyId: 
        Ref: KmsKeyId
      UserGroupIds:
        - !Ref RedisUserGroupName      
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: TenantType  
          Value: !Ref TenantType
        - Key: Project
          Value: !Ref ProjectName        

Outputs:
  RedisClusterPrimaryEndpoint:
    Description: "Primary endpoint address of the Redis cluster"
    Value: 
      !GetAtt 
        - RedisReplicationGroup
        - PrimaryEndPoint.Address

  RedisClusterReaderEndpoint:
    Description: "Reader endpoint address of the Redis cluster"
    Value: 
      !GetAtt 
        - RedisReplicationGroup
        - ReaderEndPoint.Address