AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create AWS Systems Manager Parameter Store parameters
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Project Name and Environment'
        Parameters:
          - ProjectName
          - Environment
          - TenantType
      - Label:
          default: 'SSM Parameters'
        Parameters:
          - DBUserParameterName
          - DBUser
          - DBHostParameterName
          - DBHostParameterValue
          - DBPortParameterName
          - DBPortParameterValue
          - DBNameParameterName
          - DBNameParameterValue
          - RedisEndpointParameterName
          - RedisEndpointParameterValue
          - RedisPortParameterName
          - RedisPortParameterValue
          - RedisUserParameterName
          - RedisUserParameterValue
          
Parameters:
  ProjectName:
    Description: Name of the Project (ex- rczf, rczh)
    Type: String  
  Environment:
    Description: Environment (dev, staging, qa, prod)
    Type: String
  TenantType:
    Description: Tenant Type of the project (ex- finance, health)
    Type: String    
  DBUserParameterName:
    Description: Enter the SSM Parameter Name for DB User Parameter (ex- /dev/rczf-config/db-user)
    Type: String
  DBUser:
    Description: Enter the RDS database username.
    Type: String    
  DBHostParameterName:
    Description: Enter the SSM Parameter Name for DB Host Parameter (ex- /dev/rczf-config/db-host)
    Type: String
  DBHostParameterValue:
    Description: Enter the RDS Endpoint/URL.
    Type: String
  DBPortParameterName:
    Description: Enter the SSM Parameter Name for DB Port Parameter (ex- /dev/rczf-config/db-port)
    Type: String
  DBPortParameterValue:
    Description: Enter the RDS DB Port.
    Type: String 
  DBNameParameterName:
    Description: Enter the SSM Parameter Name for DB Name Parameter (ex- /dev/rczf-config/db-name)
    Type: String
  DBNameParameterValue:
    Description: Enter the RDS DB Name.
    Type: String  

  RedisEndpointParameterName:
    Description: Enter the SSM Parameter Name for Redis Endpoint Parameter (ex- /dev/rczf-config/redis-endpoint)
    Type: String
  RedisEndpointParameterValue:
    Description: Enter the Redis Endpoint/URL.
    Type: String
  RedisPortParameterName:
    Description: Enter the SSM Parameter Name for Redis Port Parameter (ex- /dev/rczf-config/redis-port)
    Type: String
  RedisPortParameterValue:
    Description: Enter the Redis Port.
    Type: String 
  RedisUserParameterName:
    Description: Enter the SSM Parameter Name for Redis UserName Parameter (ex- /dev/rczf-config/redis-user)
    Type: String
  RedisUserParameterValue:
    Description: Enter the Redis UserName.
    Type: String    

Resources:
#SSM Parameter Store for RDS user and password
  DBHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref DBHostParameterName
      Description: "Host for the database"
      Value: !Ref DBHostParameterValue
      Type: String
      Tags:
        Name: !Ref DBHostParameterName
        Env: !Ref Environment
        TenantType: !Ref TenantType
        Project: !Ref ProjectName
  DBPortParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref DBPortParameterName
      Description: "Port for DB Port"
      Value: !Ref DBPortParameterValue
      Type: String
      Tags:
        Name: !Ref DBPortParameterName
        Env: !Ref Environment
        TenantType: !Ref TenantType
        Project: !Ref ProjectName
  DBNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref DBNameParameterName
      Description: "Username for the database"
      Value: !Ref DBNameParameterValue
      Type: String
      Tags:
        Name: !Ref DBNameParameterName
        Env: !Ref Environment
        TenantType: !Ref TenantType
        Project: !Ref ProjectName      
  DBUserParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref DBUserParameterName
      Description: "Username for the database"
      Value: !Ref DBUser
      Type: String
      Tags:
        Name: !Ref DBUserParameterName
        Env: !Ref Environment
        TenantType: !Ref TenantType
        Project: !Ref ProjectName   

  RedisEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref RedisEndpointParameterName
      Description: "Endpoint for Redis cache"
      Value: !Ref RedisEndpointParameterValue
      Type: String
      Tags:
        Name: !Ref RedisEndpointParameterName
        Env: !Ref Environment
        TenantType: !Ref TenantType
        Project: !Ref ProjectName 
  RedisPortParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref RedisPortParameterName
      Description: "Port for Redis cache"
      Value: !Ref RedisPortParameterValue
      Type: String
      Tags:
        Name: !Ref RedisPortParameterName
        Env: !Ref Environment
        TenantType: !Ref TenantType
        Project: !Ref ProjectName 
  RedisUserParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref RedisUserParameterName
      Description: "Username for Redis cache"
      Value: !Ref RedisUserParameterValue
      Type: String
      Tags:
        Name: !Ref RedisUserParameterName
        Env: !Ref Environment
        TenantType: !Ref TenantType
        Project: !Ref ProjectName 
    

       
